# First Play
- name: Play - Handle Files in all hosts
  hosts: app_group
  tasks:
  - name: all host are identified with a file
    copy:
      content: My family is {{ ansible_os_family }}
      dest: /family.txt
      mode: '777'

# Second play
- name: Play - for Alpines Nodejs app
  hosts: app_group
  tasks:
  - name: NodeJs is installed
    apk:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop:
    - nodejs
    - nodejs-npm
  - name: app directory is created
    file:
      path: /node-app
      state: directory
  - name: app is installed
    template:
      src: app.js.j2
      dest: /node-app/app.js
  - name: app dependencies file is copied
    copy:
      src: package.json
      dest: /node-app/package.json
  - name: app dependencies are installed
    npm:
      path: /node-app
      state: present
      production: true
  - name: Install forever (to run Node.js app).
    npm: name=forever global=yes state=present
  
  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: forever start /node-app/app.js
    when: "forever_list.stdout.find('/node-app/app.js') == -1"

# Third Play
- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: load_balancer
  become: yes
  tasks:
    - name: Update cache
      apt: update_cache=yes

    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Start Nginx
      service:
        name: nginx
        state: started
      become: yes

    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: ./nginx.cfg
        dest: /etc/nginx/sites-available/nginx.cfg
      become: yes

    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes

    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted
      become: yes
    
    - name: Get Nginx service status
      command: service nginx status
      register: nginx_status

    - name: Display Nginx service status
      debug:
        var: nginx_status.stdout
